import React, {useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShieldCheck,Plus,Inbox,BookOpen,Settings,Search,Moon,Sun,Link2,Trash2,ArrowUpRight,ChevronRight,ShieldAlert} from 'lucide-react';
import './style.css';
import './v02.css';

const api=async(path,options={})=>{const r=await fetch(`/api${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json();if(!r.ok)throw Error(d.detail||'The request could not be completed.');return d};
const examples=[
['Overdue invoice','FINAL NOTICE: invoice #418 is overdue. Pay the balance today at https://billing.example.test/invoice/418'],
['Parcel delivery fee','URGENT: Your package is on hold. Pay a $1.80 redelivery fee now: https://parcel-example.test/fee'],
['Password warning','Your password expires today. Verify your account now at https://secure-login.example.test'],
['Bank security alert','Your bank account was locked for unusual activity. Verify your card details now at https://secure-bank.example.test'],
['Job offer fee','Remote job offer: pay a processing fee before we can send your equipment.'],
['Unexpected prize','You have won a tablet prize. Pay a shipping fee today to claim it.'],
['Tech support alert','Virus detected on your computer. Call tech support now at https://helpdesk.example.test/support.'],
['Government fine threat','IRS notice: pay immediately or face a fine.'],
['Crypto investment pitch','Crypto investment with guaranteed returns. Send crypto to start today.'],
['Gift card request','Can you buy three gift cards for the team and send me the codes before the meeting?'],
['Team lunch','Hi team, lunch is at noon tomorrow. Please let me know if you can make it.'],
['Appointment reminder','Reminder: your appointment is Thursday at 10:30. Call the clinic using the number on your card if you need to reschedule.'],
['Invoice follow-up','Please review the attached invoice during your next accounting session. There is no payment deadline.']];

function App(){
 const[status,setStatus]=useState(null),[view,setView]=useState('Analyze'),[items,setItems]=useState([]),[selected,setSelected]=useState(null),[text,setText]=useState(''),[query,setQuery]=useState(''),[dark,setDark]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[keyInput,setKeyInput]=useState(''),[wizardStep,setWizardStep]=useState(0),[connection,setConnection]=useState('');
 const refresh=async()=>{const[s,h]=await Promise.all([api('/status'),api('/history')]);setStatus(s);setItems(h.items);if(!selected&&h.items[0])setSelected(h.items[0])};
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 const filtered=useMemo(()=>items.filter(x=>`${x.text} ${x.report.label}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 const analyze=async(value=text)=>{setError('');setBusy(true);try{const item=await api('/analyze',{method:'POST',body:JSON.stringify({text:value})});setItems(old=>[item,...old]);setSelected(item);setText('');setView('History')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const saveSetup=async(rulesOnly=false)=>{setError('');try{await api('/setup',{method:'POST',body:JSON.stringify({api_key:keyInput||null,rules_only:rulesOnly})});setKeyInput('');await refresh();setWizardStep(0);setView('Analyze');setToast('Setup saved')}catch(e){setError(e.message)}};
 const testKey=async()=>{setConnection('Testing…');try{const r=await api('/setup/test',{method:'POST',body:'{}'});setConnection(r.message)}catch(e){setConnection(e.message)}};
 const openSetup=()=>{setWizardStep(1);setKeyInput('');setConnection('');setView('Settings')};
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2400);return()=>clearTimeout(t)}},[toast]);
 if(!status)return <div className="loading">Opening your local workspace…</div>;
 if(!status.setup_complete||wizardStep>0)return <div className={`wizard-page ${dark?'dark':''}`}><div className="wizard-card"><Brand/><div className="eyebrow">FIRST-RUN SETUP · {wizardStep||1} OF 3</div>{wizardStep<=1?<><h1>Welcome to PhishLens</h1><p className="lead">Review suspicious messages privately on your computer.</p><div className="privacy-note"><ShieldCheck/><div><strong>Message text stays on this device</strong><p>Analysis and history are stored locally. Domain-age and reputation checks are off by default. If enabled in Settings, the registered domain is sent to the age registry, or through your DNS resolver to Spamhaus for reputation checks. Message text and URL paths stay here. The Gemini connection check sends a fixed short test phrase only.</p><p>If you later use Gemini, Google’s data-use terms can differ between unpaid and paid services. <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noreferrer">Read Google’s current Gemini API terms <ArrowUpRight size={13}/></a></p></div></div><label className="field-label">Gemini API key <span>optional</span></label><input type="password" autoComplete="new-password" placeholder="Paste your API key" value={keyInput} onChange={e=>setKeyInput(e.target.value)}/><div className="field-hint">Create a key in <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noreferrer">Google AI Studio <ArrowUpRight size={13}/></a>. Saved locally with restricted file permissions.</div>{error&&<div className="error">{error}</div>}<div className="wizard-actions"><button className="button primary" onClick={()=>keyInput?setWizardStep(2):saveSetup(true)}>Continue</button><button className="text-button" onClick={()=>saveSetup(true)}>Skip: rules-only mode</button></div></>:<><h1>Test your connection</h1><p className="lead">One short test phrase confirms the key works. Your key will never be shown again.</p><div className="connection-box">{connection||'Ready to test your Gemini API key.'}</div>{error&&<div className="error">{error}</div>}<div className="wizard-actions"><button className="button secondary" onClick={()=>setWizardStep(1)}>Back</button><button className="button secondary" onClick={testKey}>Test connection</button><button className="button primary" onClick={()=>saveSetup(false)}>Finish setup</button></div><button className="text-button centered" onClick={()=>saveSetup(true)}>Continue without a key</button></>}</div></div>;
 return <div className={`app-shell ${dark?'dark':''}`}><aside className="sidebar"><Brand/><button className={`compose ${view==='Analyze'?'active':''}`} onClick={()=>setView('Analyze')}><Plus size={18}/> Analyze</button><div className="nav-label">WORKSPACE</div><nav><button className={view==='History'?'selected':''} onClick={()=>setView('History')}><Inbox size={18}/>History <span className="nav-count">{items.length||''}</span></button><button className={view==='Examples'?'selected':''} onClick={()=>setView('Examples')}><BookOpen size={18}/>Examples</button></nav><div className="sidebar-spacer"/><button className="side-bottom" onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>} {dark?'Light mode':'Dark mode'}</button><button className={`side-bottom ${view==='Settings'?'selected':''}`} onClick={()=>setView('Settings')}><Settings size={17}/>Settings</button><div className="local-status"><span className="green-dot"/> {status.domain_age_lookup_enabled||status.domain_reputation_lookup_enabled?'Local rules · lookups on':'Local and private'} <span className="local-lock">⌑</span></div><div className="version">PHISHLENS · 0.2.0</div></aside>
 <main className="main-area"><header className="topbar"><div><span className="crumb">Workspace</span><ChevronRight size={14}/><strong>{view}</strong></div><div className="top-status" title={status.domain_age_lookup_enabled||status.domain_reputation_lookup_enabled?"Enabled lookups send registered domains to RDAP or Spamhaus":"No domain information is sent to external services"}><span className="green-dot"/> {status.domain_age_lookup_enabled||status.domain_reputation_lookup_enabled?"Optional lookups on":"Local checks only"}</div></header>
 {view==='Analyze'&&<section className="compose-view"><div className="page-heading"><div><div className="eyebrow">MESSAGE REVIEW</div><h1>Analyze a message</h1><p>Paste a suspicious email, text, or URL. PhishLens checks it without opening any links.</p></div><div className="round-icon"><ShieldCheck size={24}/></div></div><div className="composer"><div className="composer-header"><div className="avatar">✳</div><div><strong>New analysis</strong><span>Private · stored on this device</span></div><span className="char-count">{text.length.toLocaleString()} / 20,000</span></div><textarea maxLength={20000} placeholder={'Paste the message or URL you want to review…\n\nYour text is analyzed locally and displayed as plain text.'} value={text} onChange={e=>setText(e.target.value)}/><div className="composer-footer"><span><ShieldCheck size={15}/> Links are never opened</span><button className="button primary" disabled={busy||!text.trim()} onClick={()=>analyze()}>{busy?'Analyzing…':<><Search size={16}/> Analyze message</>}</button></div></div>{error&&<div className="error inline-error">{error}</div>}<div className="below-grid"><div className="info-card"><div className="card-icon"><ShieldCheck size={18}/></div><div><strong>Evidence, not a verdict</strong><p>Independent rules flag specific signals. “Unable to determine” means there wasn’t enough evidence.</p></div></div><div className="info-card"><div className="card-icon"><Link2 size={18}/></div><div><strong>Links stay unopened</strong><p>URLs are inspected as text. Optional RDAP age and Spamhaus DBL reputation checks send registered domains only. HTTPS does not mean a site is legitimate.</p></div></div></div><div className="quick-examples"><div className="section-title"><span>TRY AN EXAMPLE</span><button onClick={()=>setView('Examples')}>View all <ArrowUpRight size={13}/></button></div><div className="example-chips">{examples.slice(0,3).map(([title,value],i)=><button key={title} onClick={()=>analyze(value)}><span className={`chip-dot dot-${i}`}/>{title}<ArrowUpRight size={13}/></button>)}</div></div></section>}
 {view==='History'&&<div className="history-layout"><section className="list-pane"><div className="list-heading"><div className="eyebrow">YOUR DEVICE</div><h1>History <span>{items.length}</span></h1></div><div className="search-wrap"><Search size={16}/><input placeholder="Search analyses" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="message-list">{filtered.map(item=><button key={item.id} className={`message-row ${selected?.id===item.id?'active':''}`} onClick={()=>setSelected(item)}><span className={`risk-dot risk-${item.report.label.toLowerCase().replaceAll(' ','-')}`}/><div className="row-content"><div className="row-top"><strong>{item.text.slice(0,42).replace(/\s+/g,' ')||'Empty message'}</strong><time>{new Date(item.created_at).toLocaleDateString()}</time></div><div className="row-bottom"><span>{item.report.label}</span><span>· {item.report.evidence_count} indicator{item.report.evidence_count===1?'':'s'}</span></div><p>{item.text.slice(0,88)}</p></div></button>)}{filtered.length===0&&<div className="empty-list"><p>No analyses found.</p><button className="text-button" onClick={()=>setView('Analyze')}>Start an analysis</button></div>}</div><button className="new-analysis" onClick={()=>setView('Analyze')}><Plus size={16}/> New analysis</button></section><section className="report-pane">{selected?<Report item={selected}/>:<div className="report-empty"><ShieldCheck size={34}/><h2>Your report appears here</h2><p>Select an analysis from your history.</p></div>}</section></div>}
 {view==='Examples'&&<section className="content-page"><div className="eyebrow">LEARN BY EXAMPLE</div><h1>Example messages</h1><p className="page-intro">Synthetic sample messages for exploring PhishLens.</p><div className="examples-grid">{examples.map(([title,value],i)=><article className="example-card" key={title}><div className="example-card-top"><span className={`sample-icon sample-${i%3}`}>{i<9?<ShieldAlert size={17}/>:<BookOpen size={17}/>}</span><span className="sample-type">{i<9?'SUSPICIOUS SIGNALS':'EVERYDAY MESSAGES'}</span></div><h3>{title}</h3><p>{value}</p><button className="button secondary small" onClick={()=>analyze(value)}>Analyze example <ArrowUpRight size={14}/></button></article>)}</div></section>}
 {view==='Settings'&&<SettingsPage status={status} onSetup={openSetup} onClear={async()=>{await api('/history',{method:'DELETE'});setItems([]);setSelected(null);setToast('History deleted')}} onSaved={refresh} error={error} setError={setError}/>}
 </main>{toast&&<div className="toast"><ShieldCheck size={16}/>{toast}</div>}</div>;
}
function Brand(){return <div className="brand"><span className="brand-mark"><ShieldCheck size={19}/></span><span>phish<span>lens</span></span><span className="beta">LOCAL</span></div>}
const indicatorLabels={
 urgency_language:'Urgency language',account_threat:'Account threat',credential_or_payment_request:'Credential or payment request',links_present:'Links present',https_used:'HTTPS used',insecure_http:'HTTP without encryption',ip_address_host:'IP address host',url_shortener:'URL shortener',registered_domain:'Registered domain',subdomain:'Subdomain',top_level_domain:'Top-level domain',punycode_or_non_ascii_domain:'Punycode or non-ASCII domain',excessive_subdomains:'Excessive subdomains',brand_impersonation:'Possible brand impersonation',suspicious_path_keywords:'Suspicious URL path words',domain_age:'Domain age lookup',domain_reputation:'Domain reputation lookup'
};
function Report({item}){
 const r=item.report;
 return <article className="report">
  <div className="report-toolbar"><div><div className="eyebrow">ANALYSIS REPORT</div><div className="report-date">{new Date(item.created_at).toLocaleString()}</div></div><span className="private-pill" title={r.domain_age_lookup_enabled||r.domain_reputation_lookup_enabled?'Message and history stayed local; registered domains were sent to enabled lookup providers.':'Message, analysis, and history stayed on this device.'}><span className="green-dot"/> {r.domain_age_lookup_enabled||r.domain_reputation_lookup_enabled?'Local · lookups used':'Local'}</span></div>
  <div className="report-title"><div><h2>{r.label}</h2><p>{r.label==='Unable to determine'?'There is not enough evidence to assess this message.':'Review the evidence below before deciding what to do.'}</p>{r.category&&<div className="category-pill">Pattern detected · {r.category}</div>}</div><span className={`score-ring ${r.label.toLowerCase().replaceAll(' ','-')}`}>{r.score}<small>/100</small></span></div>
  <div className="metrics"><div><span>RISK SCORE</span><strong>{r.score}<small> / 100</small></strong></div><div><span>CONFIDENCE</span><strong>{Math.round(r.confidence*100)}<small>%</small></strong></div><div><span>EVIDENCE</span><strong>{r.evidence_count}<small> indicators</small></strong></div></div>
  <section className="report-section"><h3>Indicators <span>{r.indicators.length}</span></h3><div className="indicator-list">{r.indicators.map((x,i)=><div className="indicator" key={`${x.indicator}-${x.url||''}-${i}`}><span className={x.status==='detected'?'indicator-mark detected':'indicator-mark'}>{x.status==='detected'?'!':x.status==='unknown'?'?':'✓'}</span><div className="indicator-content"><strong>{indicatorLabels[x.indicator]||x.indicator.replace(/^category_/,'').replaceAll('_',' ')}</strong>{x.url&&<div className="indicator-url">{x.url}</div>}<details><summary>Why?</summary><p>{x.reason}</p></details></div><span className={`status-tag ${x.status==='detected'?'detected':''} ${x.status==='unknown'?'unknown':''}`}>{x.status==='detected'?'Detected':x.status==='unknown'?'Unknown':'Not detected'}</span></div>)}</div></section>
  <section className="report-section"><h3>Why?</h3><p className="report-copy">{r.why}</p><blockquote className="original-text">{item.text}</blockquote></section>
  {r.urls.length>0&&<section className="report-section"><h3>Links found <span>{r.url_count_total??r.urls.length}</span></h3>{r.urls.map(u=><div className="url-row" key={u}><Link2 size={15}/><span>{u}</span><small>Not opened</small></div>)}{r.url_analysis_limited&&<div className="notice"><ShieldAlert size={16}/>Only the first {r.urls.length} of {r.url_count_total} URLs were analyzed.</div>}<div className="notice"><ShieldAlert size={16}/>{r.https_notice}</div></section>}
  <section className="advice"><div className="advice-icon"><ShieldCheck size={18}/></div><div><h3>What should I do?{r.category?` · ${r.category}`:''}</h3><p>{r.what_to_do}</p></div></section>
  <div className="report-foot"><ShieldCheck size={14}/> Signals are heuristic and may miss or misread context. This report is not a guarantee.</div>
 </article>;
}
function SettingsPage({status,onSetup,onClear,onSaved,error,setError}){
 const[busy,setBusy]=useState(false);
 const[domainAgeEnabled,setDomainAgeEnabled]=useState(status.domain_age_lookup_enabled);
 const[domainReputationEnabled,setDomainReputationEnabled]=useState(status.domain_reputation_lookup_enabled);
 useEffect(()=>setDomainAgeEnabled(status.domain_age_lookup_enabled),[status.domain_age_lookup_enabled]);
 useEffect(()=>setDomainReputationEnabled(status.domain_reputation_lookup_enabled),[status.domain_reputation_lookup_enabled]);
 const updateDomainAge=async(enabled)=>{
  setBusy(true);setError('');
  try{const result=await api('/settings/domain-age',{method:'POST',body:JSON.stringify({enabled})});setDomainAgeEnabled(result.domain_age_lookup_enabled);await onSaved()}
  catch(e){setError(e.message)}finally{setBusy(false)}
 };
 const updateDomainReputation=async(enabled)=>{
  setBusy(true);setError('');
  try{const result=await api('/settings/domain-reputation',{method:'POST',body:JSON.stringify({enabled})});setDomainReputationEnabled(result.domain_reputation_lookup_enabled);await onSaved()}
  catch(e){setError(e.message)}finally{setBusy(false)}
 };
 return <section className="content-page settings-page"><div className="eyebrow">PREFERENCES</div><h1>Settings</h1><p className="page-intro">Manage how PhishLens behaves on this device.</p>
  <article className="settings-card"><div className="settings-card-heading"><span className="setting-icon"><ShieldCheck size={18}/></span><div><h3>Gemini connection</h3><p>Gemini is only used for a fixed connection check in v0.2.</p></div><span className="mode-pill">RULES ONLY</span></div><div className="setting-row"><div><strong>API key</strong><p>{status.key.configured?`Configured · ${status.key.masked} · ${status.key.source}`:'No key saved. Rules-only mode is active.'}</p></div><button className="button secondary small" onClick={onSetup}>{status.key.configured?'Change key':'Add key'}</button></div><div className="setting-row"><div><strong>Setup wizard</strong><p>Review the privacy note and test a Gemini connection.</p></div><button className="text-button" onClick={onSetup}>Open wizard <ArrowUpRight size={14}/></button></div></article>
  <article className="settings-card"><div className="settings-card-heading"><span className="setting-icon"><Search size={18}/></span><div><h3>Domain registration age</h3><p>Check the registration date through authoritative RDAP records.</p></div><span className="mode-pill">{domainAgeEnabled?'ENABLED':'OFF BY DEFAULT'}</span></div><div className="setting-row domain-setting"><div><strong>Enable domain age lookups</strong><p>When enabled, PhishLens uses IANA’s RDAP bootstrap to find the right service, then sends up to five registered domain names per message to the matching registry. Message text and URL paths stay on this device, and links are never opened. Newly registered domains (30 days or less) add a caution signal.</p></div><label className="toggle"><input type="checkbox" checked={domainAgeEnabled} disabled={busy} onChange={e=>updateDomainAge(e.target.checked)}/><span/></label></div>{error&&<div className="error">{error}</div>}</article>
  <article className="settings-card"><div className="settings-card-heading"><span className="setting-icon"><Search size={18}/></span><div><h3>Domain reputation</h3><p>Check listed domains against the Spamhaus Domain Blocklist (DBL).</p></div><span className="mode-pill">{domainReputationEnabled?'ENABLED':'OFF BY DEFAULT'}</span></div><div className="setting-row domain-setting"><div><strong>Enable Spamhaus reputation lookups</strong><p>When enabled, each registered domain is queried through this computer’s configured DNS resolver against Spamhaus DBL. The resolver and Spamhaus can see the domains. Message text and URL paths stay here. The free service has eligibility and fair-use terms and may require a Spamhaus account. Some resolvers or networks may return an unavailable result.</p></div><label className="toggle"><input type="checkbox" checked={domainReputationEnabled} disabled={busy} onChange={e=>updateDomainReputation(e.target.checked)}/><span/></label></div>{error&&<div className="error">{error}</div>}</article>
  <article className="settings-card danger-card"><div className="settings-card-heading"><span className="setting-icon danger"><Trash2 size={18}/></span><div><h3>Local history</h3><p>Analysis history is stored in your local data folder.</p></div></div><div className="setting-row"><div><strong>Delete all history</strong><p>This permanently removes saved reports from this device.</p></div><button className="button danger-button small" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await onClear()}catch(e){setError(e.message)}finally{setBusy(false)}}}>Delete history</button></div>{error&&<div className="error">{error}</div>}</article>
  <div className="settings-note"><ShieldCheck size={16}/> PhishLens listens on this device only (127.0.0.1). Analyzed links are never opened.</div></section>
}
createRoot(document.getElementById('root')).render(<App/>);
